name: Code Coverage

on:
  workflow_run:
    workflows: ["tuto-ci-docker"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run the tests
        run: npm test -- --coverage
